webapp/app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap5
from flask_moment import Moment
from ..config import config

bootstrap = Bootstrap5()
moment = Moment()

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])

    bootstrap.init_app(app)
    moment.init_app(app)
    
    if app.config['USE_MODEL'] == 'true':
        from ... import generator
    else:
        from ... import generator_test as generator
    # print('Loading from create_app')
    app.generator = generator.generator()
    app.generator.load_model()

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .api import api as api_blueprint
    app.register_blueprint(api_blueprint, url_prefix='/api')
    

    return app

webapp/app/api/__init__.py
from flask import Blueprint

api = Blueprint('api', __name__)

from . import views

webapp/app/api/views.py
from flask import jsonify, request, current_app
from . import api
import time
import base64
import cv2
# from .... import generator
# from .... import generator_test

def test_image():
    with open('app/static/combat-agent.60cad2.png', 'rb') as img:
        encoded_string = base64.b64encode(img.read())
    return encoded_string.decode('utf-8')

def generate_b64_image(np_img):
    _, img_b64 = cv2.imencode('.png', np_img)
    img_b64 = base64.b64encode(img_b64).decode('utf-8')
    return img_b64

@api.route('/stable_diffusion_generate', methods=['GET'])
def stable_diffusion():
    width = int(request.args.get('width'))
    height = int(request.args.get('height'))
    steps = int(request.args.get('steps'))
    text = request.args.get('text')
    # image_b64 = test_image()
    image_b64 = generate_b64_image(current_app.generator.generate(width, height, text, steps))
    response = jsonify({'width': width, 'height': height, 'text': text, 'steps':steps, 'image': image_b64})
    return response

webapp/app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

webapp/app/main/views.py
from flask import render_template, redirect, url_for, abort, flash, request, current_app, make_response, send_from_directory
from . import main
import os
import subprocess

@main.route('/favicon.ico')
def favicon():
    return send_from_directory(os.path.join('static'), 'asm-logo-full.62f3fd.png', mimetype='image/vnd.microsoft.icon')

@main.route('/')
def home():
    return render_template('home.html')

@main.route('/test')
def test():
    return render_template('test.html')

webapp/app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}txt2img{% endblock %}

{% block head %}
{{ super() }}
<link rel="shortcut icon" href="{{ url_for('static', filename='asm-logo-round@2.df2681.png') }}" type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename='asm-logo-round@2.df2681.png') }}" type="image/x-icon">
<!--link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}"-->
{% endblock %}

{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	<div class="container-fluid">
		<a class="navbar-brand" href="#">
			<img src="/static/asm-logo-round@2.df2681.png" alt="" width="30" height="30" class="d-inline-block align-text-top">
			{{device_name}}
		</a>
		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav me-auto mb-2 mb-lg-0">
				<li class="nav-item">
					<a class="nav-link" aria-current="page" href="{{ url_for('main.home')}}">Home</a>
				</li>
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false"> Others </a>
					<ul class="dropdown-menu" aria-labelledby="navbarDropdown">
						<!--li><a class="dropdown-item" href="{{ url_for('main.test')}}">Test</a></li-->
						<li><a class="dropdown-item" href="#">Test</a></li>
					</ul>
				</li>
			</ul>
		</div>
	</div>
</nav>
{% endblock %}

{% block content %}
{% endblock %}

{% block scripts %}
{{ super() }}
{{ moment.include_moment() }}
<script src="{{url_for('static', filename='js/jquery-3.6.1.min.js')}}" type="text/javascript"></script>
{% endblock %}

webapp/app/templates/base_back.html
{% extends "bootstrap/base.html" %}

{% block title %}N3T{% endblock %}

{% block head %}
{{ super() }}
<link rel="shortcut icon" href="{{ url_for('static', filename='asm-logo-round@2.df2681.png') }}" type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename='asm-logo-round@2.df2681.png') }}" type="image/x-icon">
<!--link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}"-->
{% endblock %}

{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	<div class="container-fluid">
		<a class="navbar-brand" href="#">
			<img src="/static/asm-logo-round@2.df2681.png" alt="" width="30" height="30" class="d-inline-block align-text-top">
			{{device_name}}
		</a>
		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav me-auto mb-2 mb-lg-0">
				<li class="nav-item">
					<a class="nav-link" aria-current="page" href="{{ url_for('main.home')}}">Home</a>
				</li>
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false"> Other </a>
					<ul class="dropdown-menu" aria-labelledby="navbarDropdown">
						<li><a class="dropdown-item" href="#">Command</a></li>
					</ul>
				</li>
			</ul>
		</div>
	</div>
</nav>
{% endblock %}

{% block content %}
<div class="container"> 
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

    {% block page_content %}{% endblock %}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{{ moment.include_moment() }}
{% endblock %}

webapp/app/templates/bootstrap/base.html
<!doctype html>
<html lang="en">
    <head>
        {% block head %}
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        {% block styles %}
            <!-- Bootstrap CSS -->
            {{ bootstrap.load_css() }}
        {% endblock styles %}

	<title>{% block title %}{{title|default}}{% endblock title %}</title>
        {% endblock head %}
    </head>
    <body>
	{% block body -%}
	{% block navbar %}
	{%- endblock navbar %}
	{% block content -%}
	{%- endblock content %}

        {% block scripts %}
            <!-- Optional JavaScript -->
            {{ bootstrap.load_js() }}
        {% endblock scripts %}
        {% endblock body %}
    </body>
</html>

webapp/app/templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block sidebar %}
{% endblock %}
{% block content %}
	<div class="container-fluid" style="padding:0">
		<div class="row vh-100">
			<div class="col-3 h-100" style="padding: 0;width: 300px">
				<div class="d-flex flex-column flex-shrink-0 h-100 p-3 text-white bg-dark" style="width: 300px">
						<div class="parameter">
							<div class="row">
								<div class="col">
									<p>Width</p>
								</div>
								<div class="col">
									<p align="right" id="width-display">value</p>
								</div>
							</div>
							<div>
								<input id="width-range" type="range" min="64" max="512" step="64" value="64" style="width: 280px">
							</div>
						</div>
						<div class="parameter">
							<div class="row">
								<div class="col">
									<p>Height</p>
								</div>
								<div class="col">
									<p align="right" id="height-display">value</p>
								</div>
							</div>
							<div>
								<input id="height-range" type="range" min="64" max="512" step="64" value="64" style="width: 280px">
							</div>
						</div>
						<div class="parameter">
							<div class="row">
								<div class="col">
									<p>Steps</p>
								</div>
								<div class="col">
									<p align="right" id="steps-display">value</p>
								</div>
							</div>
							<div>
								<input id="steps-range" type="range" min="10" max="150" step="1" value="50" style="width: 280px">
							</div>
						</div>
						<br />
						<div class="input-group mb-3">
							<span class="input-group-text text-white bg-dark">Text</span>
							<textarea class="form-control" id="input-text" placeholder="2000 years later" style="max-height: 80px"></textarea>
						</div>
						<br />
						<button type="button" class="btn btn-primary" id="generate-button">generate</button>
				</div>
			</div>
			<div class="col position-relative h-100 w-100" id="image-container" style="background: #343a40">
					<img class="position-absolute top-50 start-50 translate-middle mw-100" id="generated-image" src="/static/image-icon.png" style="width: 800px">
					<div class="position-absolute top-50 start-50 translate-middle" style="width: 3rem; height: 3rem;" role="status">
						<div class="spinner-border" id="spinner" style="display: none;width: 3rem; height: 3rem;" role="status">

							<span class="visually-hidden">Loading...</span>
						</div>
					</div>
			</div>
		</div>
	</div>
{% endblock %}


{% block scripts %}
{{ super() }}
<script src="{{url_for('static', filename='js/main.js')}}" type="text/javascript"></script>
{% endblock %}

webapp/app/templates/test.html
<!doctype html>
<html>
	<input type="range" style="width: 300px" list="tickmarks">
<datalist id="tickmarks">
<option value="0"></option>
<option value="10"></option>
<option value="20"></option>
<option value="30"></option>
<option value="40"></option>
<option value="50"></option>
<option value="60"></option>
<option value="70"></option>
<option value="80"></option>
<option value="90"></option>
<option value="100"></option>
</datalist>
</html>